---
- name: Create users
  hosts: CentOS
  become: true
  remote_user: root
  tasks:

  - name: Добавить пользователя 'lnxcfg' с добавлением его в группу 'wheel'. В CentOS 7 группа 'wheel' даёт права sudo
    user:
      name: admi
      shell: /bin/bash
      groups: root
      append: yes

  - name: Создать 2048-битовый SSH ключ для lnxcfg в ~lnxcfg/.ssh/id_rsa
    user:
      name: admi
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Установить authorized key из файла id_rsa.pub
    authorized_key:
      user: admi
      state: present
      key: "{{ lookup('file', '/home/admi/.ssh/id_rsa.pub') }}"